//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_XammerGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMovements
    {
        public int MovementId { get; set; }
        public int InventoryItemId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public decimal QuantityChange { get; set; }
        public System.DateTime MovementDate { get; set; }
        public string Comment { get; set; }
    
        public virtual InventoryItems InventoryItems { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
