//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_XammerGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionStages
    {
        public int StageId { get; set; }
        public int OrderId { get; set; }
        public int StageTypeId { get; set; }
        public Nullable<int> AssignedWorkerId { get; set; }
        public int StageStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
        public virtual ProductionStageTypes ProductionStageTypes { get; set; }
        public virtual ProductionStageStatuses ProductionStageStatuses { get; set; }
    }
}
